### ISSUE TITLE
Error when trying to login after installation

### ISSUE THREAD

**Issue by gblachonupg** [opentok/interactive-broadcast-api#16]
Hello,

I installed the application on my server but when i try to login, i get a 404 on http://localhost:3004/api/admin/XXXXX

I can see that i'm well authenticated on firebase but fail on the getAdmins() function.

It looks like i need to initialize my database with some data or fiels ?

I can't find any documentation on this.

How do i create the first user in firebase ?

Thank you very much

**Comment by ggoldens** [comment]
@gblachonupg, you'll need to create the first admin user. You can use this script from a terminal:
```
node server/scripts/create-user.js --name=SuperAdmin --email=test@test.com --password=123456 --apikey=12312312 --secret=780b7632d16a09d0dd8eca0667dc37d1769f370b
```
Please replace your name, email, password, opentok apikey and secret.

**Comment by gblachonupg** [comment]
Thank you very much , it works !
